-- MySQL Script generated by MySQL Workbench
-- Mon Oct 11 19:33:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema happypet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happypet` DEFAULT CHARACTER SET utf8 ;
USE `happypet` ;

-- -----------------------------------------------------
-- Table `happypet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Código de usuario, automático',
  `id_tercero` INT NOT NULL COMMENT 'codigo de tercero',
  `fecha_creacion` TIMESTAMP NOT NULL  COMMENT 'Fecha creación del usuario',
  `fecha_retiro` DATETIME NULL COMMENT 'fecha retiro o inactivacipon de usuario',
  `estado` VARCHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Activo/ Inactivo',
  `usuario_creo` VARCHAR(20) NOT NULL COMMENT 'identificación de quien crea el usuario',
  `usuario_retiro` VARCHAR(20) NULL COMMENT 'identificación de usuario que retira o incativa el usuario',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT COMMENT 'identificación de perfil',
  `descripcion` VARCHAR(10) NOT NULL COMMENT 'nombre del perfil',
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`bd_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`bd_user` (
  `login` VARCHAR(20) NOT NULL COMMENT 'identificador del usuario en la bd',
  `id_usuario` INT NOT NULL COMMENT 'identificación del usuario al que se le asigna el login',
  `perfil` INT NOT NULL COMMENT 'perfil asignado al usuario',
  `estado` VARCHAR(1) NOT NULL COMMENT 'Activo o inactivo en la bd',
  `Perfil_id_perfil` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_bd_user_Perfil1_idx` (`Perfil_id_perfil` ASC),
  INDEX `fk_bd_user_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_bd_user_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `happypet`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bd_user_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `happypet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Modulos` (
  `id_modulo` VARCHAR(10) NOT NULL COMMENT 'código del módulo (Menú) u objeto',
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Funciones` (
  `id_funcion` VARCHAR(5) NOT NULL COMMENT 'Codigo de la función',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'Nombre de la función',
  `id_modulo` VARCHAR(10) NULL COMMENT 'identificación del módulo al cual pertence la función',
  `Modulos_id_modulo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_funcion`),
  INDEX `fk_Funciones_Modulos1_idx` (`Modulos_id_modulo` ASC),
  CONSTRAINT `fk_Funciones_Modulos1`
    FOREIGN KEY (`Modulos_id_modulo`)
    REFERENCES `happypet`.`Modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`permisos` (
  `id_permiso` VARCHAR(10) NOT NULL COMMENT 'codigo del permiso',
  `id_funcion` VARCHAR(5) NOT NULL COMMENT 'función a la cual  pertenece el permiso',
  `ejecutar` TINYINT NOT NULL COMMENT 'puede ejecutarlo o no',
  `consultar` TINYINT NOT NULL COMMENT 'puede consultar o mostrar',
  `eliminar` TINYINT NOT NULL COMMENT 'puede eliminar',
  `modificar` TINYINT NOT NULL COMMENT 'si puede modificar',
  `adicionar` TINYINT NOT NULL COMMENT 'se permite la operacion de adicionar',
  `activar` TINYINT NOT NULL COMMENT 'permiso de activar',
  `inactivar` TINYINT NOT NULL COMMENT 'puede o no inactivar',
  `Funciones_id_funcion` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_permiso`),
  INDEX `fk_permisos_Funciones1_idx` (`Funciones_id_funcion` ASC) ,
  CONSTRAINT `fk_permisos_Funciones1`
    FOREIGN KEY (`Funciones_id_funcion`)
    REFERENCES `happypet`.`Funciones` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`funcionxperfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`funcionxperfil` (
  `id_perfil` INT NOT NULL COMMENT 'identifica al perfil al cual se la asocia la función\n',
  `id_funcion` VARCHAR(5) NOT NULL COMMENT 'identifica la función asignada al perfil',
  `Perfil_id_perfil` INT NOT NULL,
  `Funciones_id_funcion` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_perfil`),
  INDEX `fk_funcionxperfil_Perfil1_idx` (`Perfil_id_perfil` ASC) ,
  INDEX `fk_funcionxperfil_Funciones1_idx` (`Funciones_id_funcion` ASC),
  CONSTRAINT `fk_funcionxperfil_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `happypet`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionxperfil_Funciones1`
    FOREIGN KEY (`Funciones_id_funcion`)
    REFERENCES `happypet`.`Funciones` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Ciudad` (
  `cod_dane` INT NOT NULL,
  `nombre_ciudad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_dane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Terceros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Terceros` (
  `id_tercero` INT NOT NULL AUTO_INCREMENT COMMENT 'código del tercero',
  `num_documento` INT NOT NULL COMMENT 'Documento de identificación del tercero',
  `nombre_tercero` VARCHAR(80) NOT NULL COMMENT 'Nombre del tercero',
  `dir_tercero` VARCHAR(80) NULL COMMENT 'Dirección de envío o residencia del tercero',
  `tel_tercero` INT NULL COMMENT 'numero de contacto del tercero',
  `email_tercero` VARCHAR(80) NULL COMMENT 'correo electrónico del tercero',
  `tipo_tercero` VARCHAR(1) NOT NULL COMMENT 'Tipo de tercero  E-empleado C- cliente',
  `Terceroscol` VARCHAR(45) NOT NULL,
  `acepta_trat_datos` VARCHAR(1) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL COMMENT 'Fecha en que se crea al tercero',
  `usuario_id_usuario` INT NOT NULL,
  `Ciudad_cod_dane` INT NOT NULL,
  PRIMARY KEY (`id_tercero`),
  INDEX `fk_Terceros_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_Terceros_Ciudad1_idx` (`Ciudad_cod_dane` ASC),
  CONSTRAINT `fk_Terceros_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `happypet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceros_Ciudad1`
    FOREIGN KEY (`Ciudad_cod_dane`)
    REFERENCES `happypet`.`Ciudad` (`cod_dane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`Comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Comprobante` (
  `id_comprobante` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador interno de comprobante',
  `id_tercero` INT NULL,
  `num_comrpobante` VARCHAR(20) NULL COMMENT 'Fra de compra (proveedor), fra de venta (esta se genera al momento del pago)',
  `cod_transaccion` VARCHAR(3) NOT NULL,
  `fecha` DATE NULL COMMENT 'Fecha del documento, corresponde al último cambio en orden de compra o fecha de factura del proveedor',
  `estado_doc` VARCHAR(1) NOT NULL DEFAULT 'T' COMMENT 'Estado del comprobante: P-pendiente pago, A-Anulado, C-Pagado,I-inventariado,T-Trámite(default)',
  `fecha_registro` TIMESTAMP NOT NULL COMMENT 'Fecha en que se crea el documento',
  `usuario` VARCHAR(20) NOT NULL DEFAULT 'cliente' COMMENT 'login del usuario que registra el comprobante',
  `valor_descuento` FLOAT NULL COMMENT 'Si el documento tiene aplicado un descuento, se guarda el valor',
  `Terceros_id_tercero` INT NOT NULL,
  PRIMARY KEY (`id_comprobante`),
  UNIQUE INDEX `num_comrpobante_UNIQUE` (`num_comrpobante` ASC),
  INDEX `fk_Comprobante_Terceros1_idx` (`Terceros_id_tercero` ASC) ,
  CONSTRAINT `fk_Comprobante_Terceros1`
    FOREIGN KEY (`Terceros_id_tercero`)
    REFERENCES `happypet`.`Terceros` (`id_tercero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`tipo_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`tipo_items` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`unidades_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`unidades_medida` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happypet`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`categoria` (
  `id_categoria` VARCHAR(1) NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `happypet`.`Imagenes_x_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Imagenes_x_item` (
  `id_imagen` INT NOT NULL AUTO_INCREMENT,
  `codigo_item` VARCHAR(10) NOT NULL,
  `archivo` VARCHAR(200) NOT NULL,
  `Items_codigo_item` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `fk_Imagenes_x_item_Items1_idx` (`Items_codigo_item` ASC),
  CONSTRAINT `fk_Imagenes_x_item_Items1`
    FOREIGN KEY (`Items_codigo_item`)
    REFERENCES `happypet`.`Items` (`codigo_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;
  

-- -----------------------------------------------------
-- Table `happypet`.`tipo_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`tipo_items` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `happypet`.`unidades_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`unidades_medida` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `happypet`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`categoria` (
  `id_categoria` VARCHAR(1) NOT NULL,
  `descripcion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `happypet`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Items` (
  `codigo_item` VARCHAR(10) NOT NULL COMMENT 'codigo item',
  `descripcion` VARCHAR(80) NOT NULL COMMENT 'Descripcion corta del item',
  `detalle` VARCHAR(150) NOT NULL COMMENT 'descripcion detallada del item',
  `tipo_articulo` INT NOT NULL COMMENT 'codi tipo item',
  `mascota` VARCHAR(1) NOT NULL COMMENT 'cod categoria de mascota',
  `unidad` INT NOT NULL COMMENT 'unidad de medida (presentación)',
  `gravado` TINYINT NOT NULL COMMENT 'si el item tiene iva o no',
  `fecha_creacion` TIMESTAMP NOT NULL COMMENT 'fecha de creación del item',
  `peso` FLOAT NOT NULL COMMENT 'peso en kg del artículo',
  `precio_venta` FLOAT NOT NULL DEFAULT 1 COMMENT 'precio en q se vende el artículo',
  `estado` VARCHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Activo o inactivo',
  `usuario_creo` VARCHAR(20) NULL DEFAULT 'administrador' COMMENT 'quien crea el artículo',
  `categoria_id_categoria` VARCHAR(1) NOT NULL,
  `tipo_items_id_tipo` INT NOT NULL,
  `unidades_medida_id_unidad` INT NOT NULL,
  `entradas` FLOAT NOT NULL DEFAULT 0,
  `salidas` FLOAT NOT NULL DEFAULT 0,
  `saldo` FLOAT NOT NULL DEFAULT 0,  
  PRIMARY KEY (`codigo_item`),
  INDEX `fk_Items_tipo_items1_idx` (`tipo_items_id_tipo` ASC),
  INDEX `fk_Items_unidades_medida1_idx` (`unidades_medida_id_unidad` ASC),
  INDEX `fk_Items_categoria1_idx` (`categoria_id_categoria` ASC),
  

CONSTRAINT `fk_Items_unidades_medida`
    FOREIGN KEY (`unidades_medida_id_unidad`)
    REFERENCES `happypet`.`unidades_medida` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 CONSTRAINT `fk_Items_tipo_items`
    FOREIGN KEY (`tipo_items_id_tipo`)
    REFERENCES `happypet`.`tipo_items` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,  
 CONSTRAINT `fk_Items_categoria`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `happypet`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  
ENGINE = InnoDB;

DROP TABLE happypet.Items;
INSERT INTO db_happypet.categoria(id_categoria,descripcion)VALUES  ('P','Perro');
INSERT INTO db_happypet.categoria(id_categoria,descripcion)VALUES  ('G','Gato');
INSERT INTO db_happypet.categoria(id_categoria,descripcion)VALUES  ('H','Hamster');
INSERT INTO db_happypet.categoria(id_categoria,descripcion)VALUES  ('C','Conejo');

INSERT INTO db_happypet.tipo_items(descripcion)VALUES  ('Aseo');
INSERT INTO db_happypet.tipo_items(descripcion)VALUES  ('Comida');
INSERT INTO db_happypet.tipo_items(descripcion)VALUES  ('Accesorios');
INSERT INTO db_happypet.tipo_items(descripcion)VALUES  ('Otro');

-- -----------------------------------------------------
-- Table `happypet`.`Detalle_comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happypet`.`Detalle_comprobante` (
  `id_comprobante` INT NOT NULL COMMENT 'id interna del comprobante al cual pertence el detalle',
  `num_comprobante` VARCHAR(20) NULL COMMENT 'Numero del comprobante -factura ',
  `codigo_item` VARCHAR(10) NOT NULL COMMENT 'Código del item a vender o comprar',
  `cantidad` FLOAT NOT NULL COMMENT 'cantidad de venta o compra',
  `valor_u` FLOAT NOT NULL DEFAULT 1 COMMENT 'Valor unitario del item a comprar o vender',
  `Comprobante_idComprobante` INT NOT NULL,
  INDEX `fk_Detalle_comprobante_Comprobante1_idx` (`id_comprobante` ASC) ,
  INDEX `fk_detalle_items_idx` (`codigo_item` ASC),
  CONSTRAINT `fk_Detalle_comprobante_Comprobante1`
    FOREIGN KEY (`id_comprobante`)
    REFERENCES `happypet`.`Comprobante` (`id_comprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_items`
    FOREIGN KEY (`codigo_item`)
    REFERENCES `happypet`.`Items` (`codigo_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO db_happypet.items(codigo_item,descripcion,detalle,tipo_articulo,mascota,unidad,gravado,peso,precio_venta,estado,usuario_creo)
VALUES("P001","Correa","Correa larga",3,"P",4,true,10,18000,"A","admin");
INSERT INTO db_happypet.items(codigo_item,descripcion,detalle,tipo_articulo,mascota,unidad,gravado,peso,precio_venta,estado,usuario_creo)
VALUES("G101","Caña de Pesca","Ideal perseguir y atrapar",3,"G",4,true,39550,"A","admin");
INSERT INTO db_happypet.items(codigo_item,descripcion,detalle,tipo_articulo,mascota,unidad,gravado,peso,precio_venta,estado,usuario_creo)
VALUES("H201","Puente Arcoiris","Parque de juegos para Hamster",3,"H",4,true,100,21200,A,"admin");
INSERT INTO db_happypet.items(codigo_item,descripcion,detalle,tipo_articulo,mascota,unidad,gravado,peso,precio_venta,estado,usuario_creo)
VALUES("C301","Heno pangola 2kg","Alimento para Conejo",1,"C",3,true,2000,20000,"A","admin");

SELECT * FROM happypet.Items;
SELECT * FROM happypet.categoria;
SELECT * FROM happypet.unidades_medida;
SELECT * FROM happypet.tipo_items;

DROP TABLE happypet.Items;
DROP TABLE happypet.categoria;
DROP TABLE happypet.Items;
DROP TABLE happypet.Items;


DROP DATABASE  `happypet`;



